### Criar Usuário (Sucesso)
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "admin@arcaderank.com",
  "username": "admin",
  "password": "senha123segura"
}

### Tentar Criar Duplicado (Deve dar erro 409)
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "admin@arcaderank.com",
  "username": "admin",
  "password": "outrasenha"
}

### Login (Retornar Token)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@arcaderank.com",
  "password": "senha123segura"
}

### Listar Usuários (SEM TOKEN - Deve falhar 401)
GET http://localhost:3000/users

### Listar Usuários (COM TOKEN - Deve funcionar 200)
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiZDI1YmJkZmEtMTdiYi00NmM2LWJhZDQtNzRjYzA4NGMxY2FjIiwiaWF0IjoxNzY1NTQwMjg4LCJleHAiOjE3NjU1NDM4ODh9.oU9BnuWyjTvIsYBniGlYLOuaZdjfdfKtJmwvQneAhnQ